### PR TITLE
protocol: fix a memory leak

### PR DESCRIPTION
**Pull request by freemangordon**
Signed-off-by: Ivaylo Dimitrov <ivo.g.dimitrov.75@gmail.com>

### CODE REVIEW

**Comment by freemangordon** [comment]
hmm, seems I shall do that on gitlab, sorry for the noise

**Comment by Kaffeine** [comment]
It's absolutely OK to submit patches here.
I'll merge it here and to the fd.o gitlab once reviewed (I'm not a glib developer so I need to either understand the code or find someone to review this).

**Comment by freemangordon** [comment]
ok, seems I got a wrong impression from the comments in the other PRs here. Anyway, in the meanwhile I made a MR on gitlab as well :) - shall I close it?

**Comment by Kaffeine** [comment]
> ok, seems I got a wrong impression from the comments in the other PRs here.

I said that we should/have to avoid merge commits created by github. To do so, every branch should be rebased ontop of `master` before being accepted. I 'merge' them in fast-forward-only mode.

> Anyway, in the meanwhile I made a MR on gitlab as well :) - shall I close it?

Both platforms (github and gitlab) are equally acceptable. You have different commits (hashes) here and on gitlab, so one will be invalidated (technically closed without merge).

**Comment by Kaffeine** [comment]
Merged. Thank you! :+1:

**Pull request merged**
